$l = Get-Content "c:\Users\Rhonald Chiwatu\Documents\GitHub\Prime-ERP\frontend\views\inventory\components\ItemModal.tsx"
$l[2108] = "                                                       <div className=`"flex items-center gap-3 bg-slate-100 p-1 rounded-lg border border-slate-200`"><button type=`"button`" onClick={() => setFormData({ ...formData, isStationeryPack: false })} className={`px-3 py-1 text-[10px] font-bold rounded-md transition-all ${!formData.isStationeryPack ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}>UNIT BASED</button><button type=`"button`" onClick={() => setFormData({ ...formData, isStationeryPack: true })} className={`px-3 py-1 text-[10px] font-bold rounded-md transition-all ${formData.isStationeryPack ? 'bg-amber-500 text-white shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}>PACK BASED</button></div>"
$l[2109] = ""
$l[2110] = ""
$l[2111] = ""
$l[2112] = ""
$l[2113] = ""
$l[2114] = ""
$l[2115] = ""
$l[2116] = ""
$l[2117] = ""
$l[2118] = ""
$l | Set-Content "c:\Users\Rhonald Chiwatu\Documents\GitHub\Prime-ERP\frontend\views\inventory\components\ItemModal.tsx"
